name: Bump flake.lock

on:
  schedule:
    - cron: "0 6 * * 0"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: protected
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@1ca7d21a94afc7c957383a2d217460d980de4934 # v31

      - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_NIX_KEY }}
            ${{ secrets.SECRETS_NIX_KEY }}

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: Flake Bot # defaults to "GitHub Actions"
          commit_author: Flake Bot <actions@github.com> # defaults to author of the commit that triggered the run
          skip_dirty_check: false
          skip_fetch: true
